# Generated by Django 5.1.1 on 2024-10-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reset',
            old_name='token',
            new_name='access_token',
        ),
    ]
