# Generated by Django 5.1.1 on 2024-10-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_token_reset_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reset',
            old_name='access_token',
            new_name='token',
        ),
    ]
